### ISSUE TITLE
Relax bounds on katip and prometheus

### ISSUE THREAD

**Issue by adamgundry** [iconnect/ridley#26]
Unfortunately the recent `ridley` release still has restrictive bounds on `katip` and `prometheus`, which rule out the versions in LTS 17.5. I'm hoping this might just be a case of relaxing the bounds, or is there actually a breaking change in one of the dependencies?

**Comment by adinapoli** [comment]
> Unfortunately the recent ridley release still has restrictive bounds on katip and prometheus, which rule out the versions in LTS 17.5. I'm hoping this might just be a case of relaxing the bounds, or is there actually a breaking change in one of the dependencies?

No, unfortunately both the bounds on `katip` and `prometheus` are necessary. I don't recall now exactly _why_, as it has been a while since I have done the port. I'll investigate further and release `0.3.2.1` upon success. Hopefully it's not too complicated to maintain backward compatibility, as other projects are still on a fairly old version of `katip`, which might trigger a cascade of necessary updates (which might need to happen anyway at some point, I guess).

Ps. I have [shipped](https://github.com/iconnect/ridley/blob/master/stack-8.10.4.yaml) a `stack-8.10.4.yaml` file based on 17.5 (with `katip` and `prometheus` pinned to slightly older versions), which I couldn't run with CI due to the fact it seems the Github Actions workflow we are using doesn't support (yet?) GHC 8.10.4. However, I have just tried it locally and that seems to work. Can we do that as well, as a stop-gap measure?

**Comment by adinapoli** [comment]
@adamgundry Ok, see https://github.com/iconnect/ridley/pull/27. Can you try to see if it builds by simply pointing to the relevant commit SHA? If it works, I will release `0.3.2.1` on Hackage.

**Comment by adamgundry** [comment]
@adinapoli thanks for the quick fix! I tried f843dad01cb02ea914c554b8081082889bc602ac and it builds for me with an unmodified LTS 17.5 package set.

**Comment by adinapoli** [comment]
Great! [ridley-0.3.2.1](https://hackage.haskell.org/package/ridley-0.3.2.1) is now on Hackage.
